name: Standard Library Integration Tests
on: [pull_request,push]

jobs:

  wasi-testsuite:
    name: wasi-testsuite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2022]

    steps:
      - name: Checkout the playground
        uses: actions/checkout@v3

      - name: delete bash.exe stub on windows
        if: runner.os == 'Windows'
        run: del  C:\Windows\System32\bash.exe

      - name: Run all wasi-testsuite
        working-directory: python-bash-windows
        run: |
              python3 script.py
        shell: bash


